version: '3.8'

services:
  server:
    build: ./Test
    ports:
      - "8000:80"
    depends_on:
      - db
  
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "1234:5432"


volumes:
  pgdata: